require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GiftIdeasController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # GiftIdea. As you add validations to GiftIdea, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GiftIdeasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all gift_ideas as @gift_ideas" do
      gift_idea = GiftIdea.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:gift_ideas)).to eq([gift_idea])
    end
  end

  describe "GET show" do
    it "assigns the requested gift_idea as @gift_idea" do
      gift_idea = GiftIdea.create! valid_attributes
      get :show, {:id => gift_idea.to_param}, valid_session
      expect(assigns(:gift_idea)).to eq(gift_idea)
    end
  end

  describe "GET new" do
    it "assigns a new gift_idea as @gift_idea" do
      get :new, {}, valid_session
      expect(assigns(:gift_idea)).to be_a_new(GiftIdea)
    end
  end

  describe "GET edit" do
    it "assigns the requested gift_idea as @gift_idea" do
      gift_idea = GiftIdea.create! valid_attributes
      get :edit, {:id => gift_idea.to_param}, valid_session
      expect(assigns(:gift_idea)).to eq(gift_idea)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GiftIdea" do
        expect {
          post :create, {:gift_idea => valid_attributes}, valid_session
        }.to change(GiftIdea, :count).by(1)
      end

      it "assigns a newly created gift_idea as @gift_idea" do
        post :create, {:gift_idea => valid_attributes}, valid_session
        expect(assigns(:gift_idea)).to be_a(GiftIdea)
        expect(assigns(:gift_idea)).to be_persisted
      end

      it "redirects to the created gift_idea" do
        post :create, {:gift_idea => valid_attributes}, valid_session
        expect(response).to redirect_to(GiftIdea.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gift_idea as @gift_idea" do
        post :create, {:gift_idea => invalid_attributes}, valid_session
        expect(assigns(:gift_idea)).to be_a_new(GiftIdea)
      end

      it "re-renders the 'new' template" do
        post :create, {:gift_idea => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested gift_idea" do
        gift_idea = GiftIdea.create! valid_attributes
        put :update, {:id => gift_idea.to_param, :gift_idea => new_attributes}, valid_session
        gift_idea.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested gift_idea as @gift_idea" do
        gift_idea = GiftIdea.create! valid_attributes
        put :update, {:id => gift_idea.to_param, :gift_idea => valid_attributes}, valid_session
        expect(assigns(:gift_idea)).to eq(gift_idea)
      end

      it "redirects to the gift_idea" do
        gift_idea = GiftIdea.create! valid_attributes
        put :update, {:id => gift_idea.to_param, :gift_idea => valid_attributes}, valid_session
        expect(response).to redirect_to(gift_idea)
      end
    end

    describe "with invalid params" do
      it "assigns the gift_idea as @gift_idea" do
        gift_idea = GiftIdea.create! valid_attributes
        put :update, {:id => gift_idea.to_param, :gift_idea => invalid_attributes}, valid_session
        expect(assigns(:gift_idea)).to eq(gift_idea)
      end

      it "re-renders the 'edit' template" do
        gift_idea = GiftIdea.create! valid_attributes
        put :update, {:id => gift_idea.to_param, :gift_idea => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gift_idea" do
      gift_idea = GiftIdea.create! valid_attributes
      expect {
        delete :destroy, {:id => gift_idea.to_param}, valid_session
      }.to change(GiftIdea, :count).by(-1)
    end

    it "redirects to the gift_ideas list" do
      gift_idea = GiftIdea.create! valid_attributes
      delete :destroy, {:id => gift_idea.to_param}, valid_session
      expect(response).to redirect_to(gift_ideas_url)
    end
  end

end
